INSERT INTO "Table" VALUES
(1, 2, FALSE);
INSERT INTO "Table" VALUES
(2, 2, FALSE);
INSERT INTO "Table" VALUES
(3, 2, FALSE);
INSERT INTO "Table" VALUES
(4, 2, FALSE);
INSERT INTO "Table" VALUES
(5, 2, FALSE);
INSERT INTO "Table" VALUES
(6, 4, FALSE);
INSERT INTO "Table" VALUES
(7, 4, FALSE);
INSERT INTO "Table" VALUES
(8, 4, FALSE);
INSERT INTO "Table" VALUES
(9, 4, FALSE);
INSERT INTO "Table" VALUES
(10, 6, FALSE);
INSERT INTO "Table" VALUES
(11, 6, FALSE);
INSERT INTO "Table" VALUES
(12, 8, FALSE);
INSERT INTO "Table" VALUES
(13, 8, FALSE);